name: Java CI/CD pipeline

on:
  push:
    branches: [main]
    pull_request: [main]

  jobs:
    build:
      runs-on: ubuntu-lastest

      steps:
        - name: Checkout code
          uses: actions/checkouts@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'

        - name: Build with Gradle
          run: ./gradlew build

        - name: Run tests
          run: ./gradlew test

        - name: Deploy (Example step)
          run: echo "Deploy my application..."